version: '3'

services:
  ch_server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    volumes:
      - ./db:/var/lib/clickhouse
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Монтируем SQL-скрипт

  postgres12:
    image: postgres:12-alpine
    container_name: postgres12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    restart: unless-stopped
