// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type User struct {
	Iin            int64     `json:"iin"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	Name           string    `json:"name"`
	Surname        string    `json:"surname"`
	Email          string    `json:"email"`
	CreatedAt      time.Time `json:"created_at"`
	UserRole       string    `json:"user_role"`
}
